### ISSUE TITLE
Does not work for view-source protocol on Firefox 57

### ISSUE THREAD

**Issue by legoktm** [wikimedia/WikimediaDebug#10]
If I load a page via X-Wikimedia-Debug and then use "view source" in Firefox 57, it will not pass the XWD header as observed in the network console and by checking the wgHostname variable.

Using Chromium 61 view-source works fine.

**Comment by bd808** [comment]
The code for both is identical now so this sounds like an upstream bug with the WebExtension APIs in Firefox.

**Comment by Krinkle** [comment]
Moved to [T269026](https://phabricator.wikimedia.org/T269026).
