### ISSUE TITLE
New permissions required after update

### ISSUE THREAD

**Issue by zeljkofilipin** [wikimedia/WikimediaDebug#16]
I'm not sure if this is a problem or not, but I did not find release notes. All I want to know is if it's safe to click `update`. :) Looks like this was introduced in cadfc9f.

![wikimediadebug-1](https://user-images.githubusercontent.com/23927/36146816-32618f54-10b6-11e8-9a15-9b01b91bfe3c.png)

![wikimediadebug-2](https://user-images.githubusercontent.com/23927/36146818-327956f2-10b6-11e8-8cf2-4d9359c9640b.png)

![wikimediadebug-3](https://user-images.githubusercontent.com/23927/36146819-3293a566-10b6-11e8-88c7-5072c9c61626.png)

**Comment by Nikerabbit** [comment]
They added new domains for wmflabs I think. It should be safe.

**Comment by bd808** [comment]
@Nikerabbit is correct. This was a side effect of adding support for beta cluster and Toolforge.
