### ISSUE TITLE
Warn on unsupported domains

### ISSUE THREAD

**Issue by tgr** [wikimedia/WikimediaDebug#20]
I just wasted a lot of time trying to debug something on Wikitech. By the time I realized my mistake, I recalled seeing this happening to other people during SWAT, who follow the the standard rules for testing via mwdebug and then get very confused when the patch does not work. It seems like an easy mistake to make; if the extension could warn when it's used on an unsupported domain (even if that's just a blacklist for wikitech/labtestwikitech) that would be super nice.

Of course if wikitech can be fixed to work with X-Wikimedia-Debug that's even better. I'm not sure if it uses the same code as the other sites these days.

**Comment by bd808** [comment]
How would the plugin determine what is an unsupported domain? What would the warning look like?

The epic at https://phabricator.wikimedia.org/T161553 tracks the things that need to change with Wikitech before we can move it into the main cluster where X-Wikimedia-Debug and pinning to test servers would be possible.

**Comment by tgr** [comment]
As I said just blacklisting would be a start. I imagine the warning would change the icon (overlay a red X or exclamation mark or something) and show some explanation in the control popup when you click on the icon.

**Comment by Krinkle** [comment]
Moved to Phabricator: [T269028](https://phabricator.wikimedia.org/T269028).
