### ISSUE TITLE
Support single-tab mode

### ISSUE THREAD

**Issue by kostajh** [wikimedia/WikimediaDebug#21]
It would be nice to have the option (maybe default behavior?) of activating the header for a single tab, rather than the entire browser window. I've been bitten more than once by leaving the header active while browsing in other tabs, and in my usage (SWAT windows) I really only need to use this extension for a single tab.

**Comment by bd808** [comment]
It looks like this might be possible if we can figure out how and when to add a `tabId` element to the filter that we use when registering our `onBeforeSendHeaders` callback (https://github.com/wikimedia/WikimediaDebug/blob/master/background.js#L138-L139)

More details at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/RequestFilter#Type

I'm not sure what the UI/UX would be for this. @kostajh do you have an example of some other webextension that has a per-tab functionality that feels easy to use and understand?

**Comment by Krinkle** [comment]
Moved to [T269031](https://phabricator.wikimedia.org/T269031).
