### ISSUE TITLE
Pull backend server list from noc

### ISSUE THREAD

**Issue by bd808** [wikimedia/WikimediaDebug#7]
Read https://noc.wikimedia.org/conf/debug.json to get the list of backend servers that can be selected.

**Comment by Krinkle** [comment]
```js
fetch('https://noc.wikimedia.org/conf/debug.json').then(r=>r.json()).then(console.log)
```


```
Access to fetch at 'https://noc.wikimedia.org/conf/debug.json' from origin 'https://en.wikipedia.org' has been blocked by CORS policy:

No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

```

**Comment by tacsipacsi** [comment]
> We'll need to allow this file to be publicly fetched across origins:
> 
> ```js
> fetch('https://noc.wikimedia.org/conf/debug.json').then(r=>r.json()).then(console.log)
> ```
> 
> > `Access to fetch at 'https://noc.wikimedia.org/conf/debug.json' from origin 'https://en.wikipedia.org' has been `**`blocked by CORS policy`**`: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Did you try this from the actual extension? It works for me, both in Firefox and in Chromium—the permission to access `*://*.wikimedia.org/*` (see `permissions` key in manifest.json) makes it possible to fetch data from noc.wikimedia.org without any CORS issues.

**Comment by Krinkle** [comment]
Moved to Phabricator: [T268167](https://phabricator.wikimedia.org/T268167)
